aliases:
 - &filter-only-main
   branches:
     only:
       - main

version: 2
jobs:
  deploy-website:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Deploying to GitHub Pages
          command: |
            git config --global user.email "${GH_EMAIL}"
            git config --global user.name "${GH_NAME}"
            echo "machine github.com login ${GH_NAME} password ${GH_TOKEN}" > ~/.netrc
            yarn install && GIT_USER=${GH_NAME} yarn run publish-gh-pages

workflows:
  version: 2
  build_and_deploy:
    jobs:
    - deploy-website:
        filters: *filter-only-main